name: hourly queue dump to s3
on:
  # schedule:
  #   - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  dumper:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run s3-event-writer
      run: python src/app.py
      env:
        QUEUE_URL: ${{ secrets.QUEUE_URL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
