name: keep the repo alive
on:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gautamkrishnar/keepalive-workflow@1.0.7
      with:
        time_elapsed: 29
